#!/bin/bash

### BEGIN INIT INFO
# Provides:          hobot
# Required-Start:    $all
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: load wifi driver
### END INIT INFO

get_antenna_type_string() {
  board_id=$(cat /sys/class/socinfo/board_id)
  board_type=$((0x$board_id & 0xfff))
  hex_btype=$(printf "0x%x" $board_type)

  case $hex_btype in
  "0x301")
    echo "switch"
    ;; 
  "0x302")
    echo "switch"
    ;; 
  "0x501")
    echo "switch"
    ;;
  "0x502")
    echo "switch"
    ;; 
  "0x503")
    echo "switch"
    ;;
  "0x504")
    echo "switch"
    ;;
  "0x505")
    echo "switch"
    ;;
  "0x506")
    echo "fixed"
    ;;
  *)
    echo "null"
    exit -1
  ;;
  esac
}

do_load_wifi()
{
	  antenna_type=$(get_antenna_type_string)

    if [ $antenna_type == "switch" ]; then
		config_file="/boot/config.txt"
		antenna_option="antenna_option"

		if [ -f "$config_file" ]; then
			antenna_value=$(grep -E "^$antenna_option=" "$config_file" | cut -d= -f2)

			if [ -n "$antenna_value" ]; then
				if [ "$antenna_value" = "cable" ]; then
					/bin/switch_antenna cable
				elif [ "$antenna_value" = "trace" ]; then
					/bin/switch_antenna trace
				else
					echo "Unrecognized value for $antenna_option: $antenna_value"
				fi
			else
				/bin/switch_antenna trace
			fi
		else
		/bin/switch_antenna trace
		fi
	fi
}

case "$1" in
	start)
		do_load_wifi
		exit 0
		;;
	*)
		echo "Usage: $0 start"
		exit 0
	;;
esac
